travis:
  secure:
    BINSTAR_TOKEN: pIHXxC5eWoX1vsQbzDBRo19HjvaTzxDDO2PgYykEjpZUwfC9d0c2pF2RB7X9S9chVh0g382yZJz3Fdi9pDQnRGOBAfomlEPMIOsQuQzHlm9kXmv3G+zpUNiQLTilko/zfCUBvk85QlP/Rt9Q1zrKUNr7+g0JWuhI2s+k6Vd0TYaWrIhvdj69RNWBQlWD1wEaaVLm6cCunGXb/b1NeBschan7ifgz2fsDCF8ctlNHWHUn09SUFVf0U7UzLmblYcqh/LVk5Se9ORjOeKXBPj54PNLqcuNBk2dpPiLYBFV1PkGjRn47Vm/Z2ilq3vgSWwOCCYkuvugvj4DrzkwXLi9tgQp+NcpQXqQLmKS+3SykaYccWR3D2O16Zv+fPX5b7s+dW5rY1lFTYm+V51WtNWiDBaGEgfKZ4E0bagOUC025piWsZo4cIeF1MqoQdYUVuUZ2/KsObp7eDn+FH3xH/YZK498REWA34aAg3q7lcuqJ4EucmtXz8mdNX5LfH8y3NUd+lQ0O/fVeSWBm9boD1xb3t9Eg4AS3IFlhYLU07yWKtWBELE9PuaN+fSGtwiVE+edUPZjcakA5zWzyY1UwcWvy8AvB9OowA93Sd94uCz6F/lgUf2fVG7HdEq5FnhwYH/1NQUyLiGUXH5EhOhxkG8GEt05gW/kTVlZ1k6OTC+yDY0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
