appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: GAk/5Cgz4oJYqTJxnMEc0VVsiXzgrTKqtGSZBjI9mLHUyb1m6eJAsabwvmOJCz3rLf0p/VGjSTYBzJs9pD9JnYfRqBsQYLyO/m01K2dSPQX8SC1N79YIIIMQd00sJbxVDFv0ttIzkLSL8uzyQ/q11l7TfSsz8CU8aw1yNyMR66dK+D1JZBZPEmuN8lwpJ1vMFaVEIga7KJinJMxyTwa0T0JDBip0d8Zu5drdz9Er5Jt3aJUFyYD6SkWAka8QN+1Jcwgd+DwDN4BDeasOr90ObrPIqumcISy1PzDO5prqCixPF0Mtb5QfNN2d6AvddCiPlGwpPuv66UzAm+/aLhSEHHtMv+cXq4tzXZrSAGAHQThxBiGdFSx5JobGGloiRy1TWb/ZgCn50AIv0x9c2hEkUUDFdXFqxAG8sa58aAOU+USy4rxVgbPIFJ06dkfrAdWtEXzTszyM2qY0T1rki/HSr1/NIWk7pRMNi2iivpPDoEgmKOlYkWft8poFjaR45iG6p/6XEidXJJk5e7QwlP3tXNdkpkf6q49+B0VD1GZpd4I7MqE/zxCbeuD7KtkI8A0sjgw5kR7K9xkqsF9UuTAuyXDJDy9MuOht4a5vF9m08y6LKijOz2pNCF0wr1liauXpTT3rthpZBWTLzDJ0DzmxsM0VJ7E/fOtUWXxFD9nacEU=
